version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ziwiki
    expose:
      - "5342"
    ports:
      - "5432:5432"
  api:
    image: 
      run_image_alpine
    # build:
    #   context: .
    #   dockerfile: ./build_image_on_alpine/DockerfileRun
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/ziwiki?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - wiki_data:/tmp/wiki
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/server" ]

  monitor:
    image: 
      monitor_image_alpine
    # build:
    #   context: .
    #   dockerfile: ./build_image_on_alpine/DockerfileRun
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/ziwiki?sslmode=disable
    depends_on:
      - postgres
      - api
    volumes:
      - wiki_data:/tmp/wiki
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start_monitor.sh"
      ]
    command: [ "/app/monitor" ]
volumes:
  wiki_data:
  