version: "3.3"
services:
  nginx:
    container_name: nginx
    build: ./docker_nginx
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - nextapp
    depends_on:
      - api
      - nextapp
  postgres:
    build:
      context: ./build_image_on_alpine
      dockerfile: ./postgres.Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ziwiki
    expose:
      - "5342"
  api:
    build:
      context: ./
      dockerfile: ./build_image_on_alpine/api.Dockerfile
    expose:
      - "8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/ziwiki?sslmode=disable
      - USE_HTTPS=${NEXT_PUBLIC_USE_HTTPS}
    depends_on:
      - postgres
    volumes:
      - wiki_data:/tmp/wiki
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/server" ]
  nextapp:
    container_name: nextapp
    build:
      context: ./fronted
      dockerfile: prod.Dockerfile
      args:
        NEXT_PUBLIC_HOME_URL: ${NEXT_PUBLIC_HOME_URL}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        NEXT_PUBLIC_USE_HTTPS: ${NEXT_PUBLIC_USE_HTTPS}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    restart: always
    expose:
      - "3000"
    links:
      - api
    depends_on:
      - api
  monitor:
    build:
      context: ./
      dockerfile: ./build_image_on_alpine/monitor.Dockerfile
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/ziwiki?sslmode=disable
    depends_on:
      - postgres
      - api
    volumes:
      - wiki_data:/tmp/wiki
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start_monitor.sh"
      ]
    command: [ "/app/monitor" ]
volumes:
  wiki_data:
