CREATE TABLE "repos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "repo_name" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "markdowns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mdhref" varchar UNIQUE NOT NULL,
  "user_id" int NOT NULL,
  "repo_id" int NOT NULL,
  "mdtext" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT 'now()'
);

ALTER TABLE "repos" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "markdowns" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "markdowns" ADD FOREIGN KEY ("repo_id") REFERENCES "repos" ("id");
