// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMarkdown(ctx context.Context, arg CreateMarkdownParams) (Markdown, error)
	CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMarkdown(ctx context.Context, arg DeleteMarkdownParams) error
	DeleteMarkdownByRepo(ctx context.Context, arg DeleteMarkdownByRepoParams) error
	DeleteRepo(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetMarkdown(ctx context.Context, arg GetMarkdownParams) (Markdown, error)
	GetMarkdownForUpdate(ctx context.Context, arg GetMarkdownForUpdateParams) (Markdown, error)
	GetRepo(ctx context.Context, id int64) (Repo, error)
	GetRepoForUpdate(ctx context.Context, id int64) (Repo, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, id int64) (User, error)
	ListRepos(ctx context.Context, arg ListReposParams) ([]Repo, error)
	QueryMarkdownRepo(ctx context.Context, arg QueryMarkdownRepoParams) ([]QueryMarkdownRepoRow, error)
	QueryMarkdownUser(ctx context.Context, arg QueryMarkdownUserParams) ([]QueryMarkdownUserRow, error)
	UpdateMarkdown(ctx context.Context, arg UpdateMarkdownParams) (Markdown, error)
	UpdateRepo(ctx context.Context, arg UpdateRepoParams) (Repo, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
